[package]
name = "vpn-proto"
version.workspace = true
edition.workspace = true

[dependencies]
snow.workspace = true
hmac.workspace = true
sha1.workspace = true
sha2.workspace = true
hkdf.workspace = true
blake2.workspace = true
rand.workspace = true
data-encoding.workspace = true
base64.workspace = true
thiserror.workspace = true
zeroize.workspace = true
